### ISSUE TITLE
Multi process

### ISSUE THREAD

**Issue by Mindavi** [JortPolderdijk/FHICT-samenvattingen#2]
https://github.com/JortPolderdijk/FHICT-samenvattingen/blob/master/t-sem3/Samenvatting%20OS.md#multi-process

Moet IPC zijn ipv OCP

**Comment by Mindavi** [comment]
ICP*

**Comment by Mindavi** [comment]
https://github.com/JortPolderdijk/FHICT-samenvattingen/blob/master/t-sem3/Samenvatting%20OS.md#process-scheduling
Iterrupts - > interrupts

**Comment by Mindavi** [comment]
Isochronous endpoints
Grote hoeveelheden data ipv grootte

**Comment by Mindavi** [comment]
https://github.com/JortPolderdijk/FHICT-samenvattingen/blob/master/t-sem3/Samenvatting%20OS.md#message-queues

Een makkelijker probleem - > een makkelijkere manier/oplossing

**Comment by Mindavi** [comment]
^^^ Destroy the queue when all have unlinked - > have closed

**Comment by Mindavi** [comment]
De naam van een Message Queue moet altijd met een / begin - > beginnen

**Comment by JortPolderdijk** [comment]
Fixed, see 5542d93791c96e6c2d649eef744755bfd0d61cfe. Thank you!
